# Example of the values needed for this chart

# Will be used by the template to generate secrets in `airflowprefix-dev`, `airflowprefix-test`, ...
namespacePrefixes:
  airflow: "airflowprefix"
  ggircs: "ggircsprefix"
  ciip: "ciipprefix"
  cif: "cifprefix"

docker:
  secretName: dockerhub-registry
  registry: "https://index.docker.io/v1/"
  username: "username" # The username for the dockerhub account
  password: "password" # The password for the dockerhub account

serviceAccounts:
  namespace: "" # The namespace where the service accounts should be created

linter:
  namespace: "" # The namespace where templates will be linted

deployer:
  namespace: "" # The namespace where the deployer should be created

eccc:
  host: ""
  username: ""
  password: ""
  zip_passwords: "" # a JSON array containing possible passwords for the ECCC zip files

sysdigTeam:
  users:
    - name: some@email.com
      role: ROLE_TEAM_MANAGER

acme:
  url: "" # The url against which acme challenges will be executed

# API keys for the MDT GHG credentials issuer
ghgCredentialIssuerKey:
  dev: ~
  test: ~
  prod: ~

# API keys for the growthbook feature-flagging service
growthbookApiKey:
  dev: ~
  test: ~
  prod: ~

kcClientSecrets:
  ggircs:
    dev: ~
    test: ~
    prod: ~
  cif:
    dev: ~
    test: ~
    prod: ~
  ciip:
    dev: ~
    test: ~
    prod: ~

airflowOAuth:
  dev:
    clientId: ~
    clientSecret: ~
  test:
    clientId: ~
    clientSecret: ~
  prod:
    clientId: ~
    clientSecret: ~

gcpTerraform:
  projectId: "ggl-project-id-where-terraform-state-buckets-live"
  serviceAccountCredentials: "single line string of gcp-tf-credentials.json"
