# Example of the values needed for this chart

# Will be used by the template to generate secrets in `airflowprefix-dev`, `airflowprefix-test`, ...
namespacePrefixes:
  airflow: "airflowprefix"
  ggircs: "ggircsprefix"
  ciip: "ciipprefix"

docker:
  registry: "https://index.docker.io/v1/"
  username: "username" # The username for the dockerhub account
  password: "password" # The password for the dockerhub account

terraform:
  token: "" # Terraform team token
  workspaceId: "" # Id visible in the terraform workspace's "General Settings"

serviceAccounts:
  namespace: "" # The namespace where the service accounts should be created
linterNamespace: "linterNamespaceName"
