# Example of the values needed for this chart

# Will be used by the template to generate secrets in `airflowprefix-dev`, `airflowprefix-test`, ...
namespacePrefixes:
  airflow: "airflowprefix"
  ggircs: "ggircsprefix"
  ciip: "ciipprefix"

docker:
  secretName: dockerhub-registry
  registry: "https://index.docker.io/v1/"
  username: "username" # The username for the dockerhub account
  password: "password" # The password for the dockerhub account

serviceAccounts:
  namespace: "" # The namespace where the service accounts should be created

linter:
  namespace: "" # The namespace where templates will be linted

deployer:
  namespace: "" # The namespace where the deployer should be created

eccc:
  host: ""
  username: ""
  password: ""
  zip_passwords: "" # a JSON array containing possible passwords for the ECCC zip files

sysdigTeam:
  users:
    - name: some@email.com
      role: ROLE_TEAM_MANAGER 
