# Only add secret in prod namespaces
{{- if hasSuffix "-prod" .Release.Namespace }}

kind: Secret
apiVersion: v1
metadata:
  name: cas-acme-url
  labels:
{{ include "cas-provision.labels" . | indent 4 }}
type: Opaque
stringData:
  url: "{{ .Values.acme.url }}"

{{- end }}
