{{- if and (hasPrefix .Values.namespacePrefixes.airflow .Release.Namespace)}}
kind: Secret
apiVersion: v1
metadata:
  name: airflow-oauth
  labels: {{ include "cas-provision.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if hasSuffix "-dev" .Release.Namespace }}
  clientId: {{ .Values.airflowOAuth.dev.clientId }}
  clientSecret: {{ .Values.airflowOAuth.dev.clientSecret }}
{{- end }}
{{- if hasSuffix "-test" .Release.Namespace }}
  clientId: {{ .Values.airflowOAuth.test.clientId }}
  clientSecret: {{ .Values.airflowOAuth.test.clientSecret }}
{{- end }}
{{- if hasSuffix "-prod" .Release.Namespace }}
  clientId: {{ .Values.airflowOAuth.prod.clientId }}
  clientSecret: {{ .Values.airflowOAuth.prod.clientSecret }}
{{- end }}

{{- end }}
