# Do not apply this network policy in the warehouse or obps namespaces
{{- if not (or (hasPrefix .Values.namespacePrefixes.warehouse .Release.Namespace) (hasPrefix .Values.namespacePrefixes.obps .Release.Namespace))}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-ingress
spec:
  # This policy allows any pod with a route & service combination
  # to accept traffic from the OpenShift router pods. This is
  # required for things outside of OpenShift (like the Internet)
  # to reach your pods.
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  podSelector: {}
  policyTypes:
    - Ingress
{{- end }}
