{{- if or (hasSuffix "-dev" .Release.Namespace) (hasSuffix "-test" .Release.Namespace)}}
{{- if hasPrefix .Values.namespacePrefixes.obps .Release.Namespace }}
kind: Secret
apiVersion: v1
metadata:
  name: django-superuser
  labels: {{ include "cas-provision.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if hasSuffix "-test" .Release.Namespace }}
  username: {{ .Values.djangoSuperUser.obps.test.username }}
  password: {{ .Values.djangoSuperUser.obps.test.password }}
  {{- else }}
  username: {{ .Values.djangoSuperUser.obps.dev.username }}
  password: {{ .Values.djangoSuperUser.obps.dev.password }}
  {{- end }}
{{- end }}
{{- end }}
