# This secret needs to be deployed in all namespaces

kind: Secret
apiVersion: v1
metadata:
  name: dockerhub-registryHELM
  namespace: {{ .Release.Namespace }}
  labels:
    created-by: cas-pipeline
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson" . }}

