# This secret needs to be deployed in all namespaces

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.docker.secretName }}
  labels:
    created-by: cas-pipeline
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson" . }}
