kind: Secret
apiVersion: v1
metadata:
  name: dockerhub-registry
  namespace: {{ .Release.Namespace }}
  labels:
    created-by: cas-pipeline
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson" . }}

