{{- if and (hasPrefix .Values.namespacePrefixes.ggircs .Release.Namespace) (or (hasSuffix "-test" .Release.Namespace) (hasSuffix "-prod" .Release.Namespace))}}
kind: Secret
apiVersion: v1
metadata:
  name: eccc-swrs-import
  labels: {{ include "cas-provision.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.eccc.host }}
  username: {{ .Values.eccc.username }}
  password: {{ .Values.eccc.password }}
  zip_passwords: {{ .Values.eccc.zip_passwords | quote }}
{{- end }}
{{- if and (hasPrefix .Values.namespacePrefixes.ggircs .Release.Namespace) (hasSuffix "-dev" .Release.Namespace)}}
kind: Secret
apiVersion: v1
metadata:
  name: eccc-swrs-import
  labels: {{ include "cas-provision.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: ""
  username: ""
  password: ""
  zip_passwords: '["password"]'
{{- end }}
