# Only render template in -dev, -test, and -prod
{{- if and (hasPrefix .Values.namespacePrefixes.cif .Release.Namespace) (not (hasSuffix "-tools" .Release.Namespace))}}

kind: Secret
apiVersion: v1
metadata:
  name: growthbook
  labels:
    created-by: cas-pipeline
type: Opaque
stringData:
{{- if hasSuffix "-dev" .Release.Namespace }}
  api-key: {{ .Values.growthbookApiKey.dev }}
{{- end }}
{{- if hasSuffix "-test" .Release.Namespace }}
  api-key: {{ .Values.growthbookApiKey.test }}
{{- end }}
{{- if hasSuffix "-prod" .Release.Namespace }}
  api-key: {{ .Values.growthbookApiKey.prod }}
{{- end }}

{{- end }}
