# Only render template in -dev, -test, and -prod
{{- if not (hasSuffix "-tools" .Release.Namespace)}}

kind: Secret
apiVersion: v1
metadata:
  name: keycloak-gold-client-secret
  labels:
    created-by: cas-pipeline
type: Opaque
stringData:
# CIF client secrets
{{- if hasPrefix .Values.namespacePrefixes.cif .Release.Namespace }}
{{- if hasSuffix "-dev" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.cif.dev }}
{{- end }}
{{- if hasSuffix "-test" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.cif.test }}
{{- end }}
{{- if hasSuffix "-prod" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.cif.prod }}
{{- end }}
{{- end }}
# CIIP client secrets
{{- if hasPrefix .Values.namespacePrefixes.ciip .Release.Namespace }}
{{- if hasSuffix "-dev" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.ciip.dev }}
{{- end }}
{{- if hasSuffix "-test" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.ciip.test }}
{{- end }}
{{- if hasSuffix "-prod" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.ciip.prod }}
{{- end }}
{{- end }}
# GGIRCS client secrets
{{- if hasPrefix .Values.namespacePrefixes.ggircs .Release.Namespace }}
{{- if hasSuffix "-dev" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.ggircs.dev }}
{{- end }}
{{- if hasSuffix "-test" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.ggircs.test }}
{{- end }}
{{- if hasSuffix "-prod" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.ggircs.prod }}
{{- end }}
{{- end }}

{{- end }}
