# Only render template in -dev, -test, and -prod
{{- if or (or (hasSuffix "-dev" .Release.Namespace) (hasSuffix "-test" .Release.Namespace )) (hasSuffix "-prod" .Release.Namespace) }}

kind: Secret
apiVersion: v1
metadata:
  name: cas-namespaces
  labels:
    created-by: cas-pipeline
type: Opaque
stringData:
  airflow-namespace: "{{ .Values.namespacePrefixes.airflow }}-{{ template "namespaceSuffix" . }}"
  ggircs-namespace: "{{ .Values.namespacePrefixes.ggircs }}-{{ template "namespaceSuffix" . }}"
  ciip-namespace: "{{ .Values.namespacePrefixes.ciip }}-{{ template "namespaceSuffix" . }}"
  cif-namespace: "{{ .Values.namespacePrefixes.cif }}-{{ template "namespaceSuffix" . }}"
{{- end }}
