# Only render template in -tools
{{- if hasSuffix "-tools" .Release.Namespace }}

kind: Secret
apiVersion: v1
metadata:
  name: cas-namespace-prefixes
  labels:
    created-by: cas-pipeline
type: Opaque
stringData:
  airflow-namespace-prefix: "{{ .Values.namespacePrefixes.airflow }}"
  ggircs-namespace-prefix: "{{ .Values.namespacePrefixes.ggircs }}"
  ciip-namespace-prefix: "{{ .Values.namespacePrefixes.ciip }}"
  cif-namespace-prefix: "{{ .Values.namespacePrefixes.cif }}"
{{- end }}
