# Only render template in -dev, -test, and -prod
{{- if or (or (hasSuffix "-dev" .Release.Namespace) (hasSuffix "-test" .Release.Namespace )) (hasSuffix "-prod" .Release.Namespace) }}

kind: Secret
apiVersion: v1
metadata:
  name: cas-namespacesHELM
  namespace: {{ .Release.Namespace }}
  labels:
    created-by: cas-pipeline
type: Opaque
stringData:
  airflow-namespace: "{{ .Values.airflowNamespacePrefix }}-{{ template "namespaceSuffix" . }}"
  ggircs-namespace: "{{ .Values.ggircsNamespacePrefix }}-{{ template "namespaceSuffix" . }}"
  ciip-namespace: "{{ .Values.ciipNamespacePrefix }}-{{ template "namespaceSuffix" . }}"

{{- end }}