kind: NetworkSecurityPolicy
apiVersion: security.devops.gov.bc.ca/v1alpha1
metadata:
  name: custom-roles-k8s-api-communication
  labels:
    created-by: cas-pipeline
spec:
  description: |
    Allow 'deployer' & 'job-runner' roles to communicate with the k8s api via the corresponding Service Accounts.
  source:
    - - $namespace={{ .Release.Namespace }}
      - "@app:k8s:serviceaccountname={{ .Release.Name }}-job-runner"
    - - $namespace={{ .Release.Namespace }}
      - "@app:k8s:serviceaccountname={{ .Release.Name }}-deployer"
  destination:
    - - int:network=internal-cluster-api-endpoint
