kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-shipit-rolebinding
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}-deployer
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-{{.Release.Namespace}}-shipit
    namespace: {{ .Release.Namespace }}

{{- if .Values.linterNamepace eq .Release.Namespace}}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-circleci-rolebinding
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}-linter
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-{{.Release.Namespace}}-circleci
    namespace: {{ .Release.Namespace }}

{{ end }}
