kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{.Release.Namespace}}-shipit
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"


{{- if .Values.linterNamepace eq .Release.Namespace}}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{.Release.Namespace}}-circleci
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"

{{ end }}
