kind: Secret
apiVersion: v1
metadata:
  name: gcp-credentials-secret
  labels:
{{ include "cas-provision.labels" . | indent 4 }}
type: Opaque
stringData:
  gcp_project_id: "{{ .Values.gcpTerraform.projectId }}"
  tf_backend: |
    'bucket = "{{ .Release.Namespace }}-state"'
    'prefix = "terraform/state"'
    'credentials = "/etc/gcp/credentials.json"'
  sa_json: {{ .Values.gcpTerraform.serviceAccountCredentials | quote }}
