apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true
  - description: SHA1 of git revision to be deployed.
    displayName: Git SHA1
    name: GIT_SHA1
    required: true

objects:
  - apiVersion: authorization.openshift.io/v1
    kind: Role
    metadata:
      annotations:
        openshift.io/description: A user who can deploy applications
        openshift.io/reconcile-protect: "false"
      name: ${PREFIX}deployer
    rules:
      - apiGroups:
          - image.openshift.io
        resources:
          - imagestreamimages
          - imagestreammappings
          - imagestreams
          - imagestreamtags
        verbs:
          - get
          - list
          - watch
          - update
      - apiGroups:
          - image.openshift.io
        resources:
          - imagestreamtags
        verbs:
          - delete
      - apiGroups:
          - project.openshift.io
          - ""
        attributeRestrictions: null
        resources:
          - projects
        verbs:
          - get
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - replicationcontrollers
          - persistentvolumeclaims
          - services
          - secrets
          - configmaps
          - pods
          - pods/exec
          - pods/log
        verbs:
          - watch
          - list
          - get
          - create
          - update
          - patch
          - delete
      - apiGroups:
          - apps.openshift.io
        attributeRestrictions: null
        resources:
          - deploymentconfigs
        verbs:
          - get
          - create
          - update
          - patch
      - apiGroups:
          - apps
        attributeRestrictions: null
        resources:
          - statefulsets
        verbs:
          - get
          - create
          - update
          - patch
      - apiGroups:
          - route.openshift.io
        attributeRestrictions: null
        resources:
          - routes
        verbs:
          - get
          - create
          - update
          - patch
      - apiGroups:
          - template.openshift.io
        attributeRestrictions: null
        resources:
          - processedtemplates
        verbs:
          - create
      - apiGroups:
          - route.openshift.io
        attributeRestrictions: null
        resources:
          - routes
        verbs:
          - get
          - create
          - update
          - patch
      - apiGroups:
          - route.openshift.io
          - ""
        attributeRestrictions: null
        resources:
          - routes/custom-host
        verbs:
          - create
      - apiGroups:
          - batch
        attributeRestrictions: null
        resources:
          - jobs
          - cronjobs
        verbs:
          - get
          - create
          - update
          - patch
          - delete
          - watch
          - list
      - apiGroups:
          - policy
        resources:
          - poddisruptionbudgets
        verbs:
          - get
          - create
          - update
          - patch
          - delete
      - apiGroups:
          - ""
        resources:
          - serviceaccounts
        verbs:
          - get
          - list
          - create
          - update
          - patch
          - delete
      - apiGroups:
          - "rbac.authorization.k8s.io"
          - "authorization.openshift.io"
        resources:
          - roles
          - rolebindings
        verbs:
          - get
          - list
          - create
          - update
          - patch
          - delete
      - apiGroups:
          - extensions
          - apps
        resources:
          - deployments
          - replicasets
        verbs:
          - get
          - list
          - create
          - update
          - patch
          - delete
