apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  labels:
{{ include "cas-provision.labels" . | indent 4 }}
  name: {{ .Release.Name }}-secret-admin
rules:
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - secrets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
