{{ if eq .Release.Namespace .Values.serviceAccounts.namespace }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret-admin
  labels:
{{ include "cas-provision.labels" . | indent 4 }}

{{ end }}
