# Deploy only in the linter namespace
{{ if eq .Release.Namespace .Values.linterNamespace }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{.Release.Namespace}}-circleci
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"

{{ end }}
