{{ if eq .Release.Namespace .Values.linter.namespace }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-linter
  labels:
{{ include "cas-provision.labels" . | indent 4 }}
  namespace: {{ .Values.linter.namespace }}

{{ end }}
