apiVersion: v1
data:
  crunchy-alert-rules-pg.yml: |
{{ .Files.Get "alertManagerRulesConfig.yml" | indent 4 }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    vendor: crunchydata
{{ include "crunchy-monitoring.labels" . | indent 4 }}
  name: alertmanager-rules-config
  namespace: {{ .Values.namespace }}
