# Default values for cas-efk.
namespace: default

elasticSearchVolume: elasticsearch-data
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch
  version: 8.4.3
  replicas: 3
  host: elasticsearch
  port:
    rest: 9200
    internode: 9300
  storageRequest: 1Gi
  volume: elasticsearch-data
  storageClass: netapp-block-standard

  cpuRequest: 500m
  memoryRequest: 1Gi
