# Only render template in -dev, -test, and -prod
{{- if and (hasPrefix .Values.namespacePrefixes.cif .Release.Namespace) (not (hasSuffix "-tools" .Release.Namespace))}}

kind: Secret
apiVersion: v1
metadata:
  name: keycloak-gold-client-secret
  labels:
    created-by: cas-pipeline
type: Opaque
stringData:
{{- if hasSuffix "-dev" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.cif.dev }}
{{- end }}
{{- if hasSuffix "-test" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.cif.test }}
{{- end }}
{{- if hasSuffix "-prod" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.cif.prod }}
{{- end }}

{{- end }}
