# Only render template in -dev, -test, and -prod
{{- if and (hasPrefix .Values.namespacePrefixes.ggircs .Release.Namespace) (not (hasSuffix "-tools" .Release.Namespace))}}

kind: Secret
apiVersion: v1
metadata:
  name: cas-pipeline-keycloak-client-secret
  labels:
    created-by: cas-pipeline
type: Opaque
stringData:
{{- if hasSuffix "-dev" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.ggircs.dev }}
{{- end }}
{{- if hasSuffix "-test" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.ggircs.test }}
{{- end }}
{{- if hasSuffix "-prod" .Release.Namespace }}
  kcClientSecret: {{ .Values.kcClientSecrets.ggircs.prod }}
{{- end }}

{{- end }}
