# Note: the `.containers` template cannot use any "globals" like `.Release.Name` directly as the `.` context is replaced with the `dict` parameter on use. See README.md for more details
{{- define "cas-logging-sidecar.containers" -}}
- name: {{ .containerToSidecar }}-oc-logs-container
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 20m
  image: registry.k8s.io/kubectl:v1.29.11
  env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  command:
    - "/bin/sh"
    - "-c"
    - |
      echo 'Starting log capture';
      kubectl logs -f $POD_NAME -c {{ .containerToSidecar }} --pod-running-timeout=20s >> /var/log/{{ .logName }}.log;
  volumeMounts:
  - name: shared-logs
    mountPath: /var/log
- name: {{ .containerToSidecar }}-logrotate-container
  resources:
    limits:
      memory: 32Mi
    requests:
      memory: 8Mi
      cpu: 20m
  image: skymatic/logrotate
  command:
    - "/bin/sh"
    - "-c"
    - "while true; do logrotate -s /var/log/logrotate.status -f /etc/logrotate.conf; sleep 5; done"
  volumeMounts:
  - name: shared-logs
    mountPath: /var/log
  - name: logrotate-config
    mountPath: /etc/logrotate.conf
    subPath: logrotate.conf
- name: fluent-bit
  resources:
    limits:
      memory: 100Mi
    requests:
      memory: 25Mi
      cpu: 30m
  image: fluent/fluent-bit:latest
  env:
    # "appName": The name of the application that is being logged.
    # Added to the Elastic index name to make it easier to search for logs. Example: "frontend"
    - name: FLUENT_APP_NAME
      value: {{ .appName }}
    - name: FLUENT_ELASTICSEARCH_HOST
      value: {{ .host }}
    - name: FLUENT_ELASTICSEARCH_PORT
      value: "9200"
    - name: FLUENT_ELASTICSEARCH_USER
      valueFrom:
        secretKeyRef:
          name: fluentbit-credentials
          key: username
    - name: FLUENT_ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: fluentbit-credentials
          key: password
  command: [ "/fluent-bit/bin/fluent-bit", "-c", "/var/log/fluent-bit.conf" ]
  volumeMounts:
    - name: shared-logs
      mountPath: /var/log
    - name: fluent-bit-config
      mountPath: /var/log/fluent-bit.conf
      subPath: fluent-bit.conf
    - name: parsers-config
      mountPath:  /var/log/parsers.conf
      subPath: parsers.conf
    - name: fluent-bit-lua-scripts
      mountPath: /fluent-bit/scripts
      readOnly: true
{{- end }}
# Note: The `.volumes` template can use `.Release.Name` directly as it is passed in with the `.` context parameter
{{- define "cas-logging-sidecar.volumes" -}}
- name: shared-logs
  emptyDir: {}
- name: logrotate-config
  configMap:
    name: {{ .Release.Name }}-logrotate-configmap
- name: fluent-bit-config
  configMap:
    name: {{ .Release.Name }}-fluent-bit-configmap
- name: parsers-config
  configMap:
    name: {{ .Release.Name }}-fluent-bit-configmap
- name: fluent-bit-lua-scripts
  configMap:
    name: {{ .Release.Name }}-fluent-bit-lua-scripts
{{- end }}
