apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-logger-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list","watch"]
