apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-to-alertmanager
  namespace: {{ .Values.namespace }}
  labels:
{{ include "crunchy-monitoring.labels" . | indent 4 }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: crunchy-prometheus
    ports:
    - port: 9093
      protocol: TCP
  podSelector:
    matchLabels:
      name: crunchy-alertmanager
