apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grafana-to-prometheus
  namespace: {{ .Values.namespace }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: crunchy-grafana
    ports:
    - port: 9090
      protocol: TCP
  podSelector:
    matchLabels:
      name: crunchy-prometheus
