apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: namespace
    displayName: namespace
    name: NAMESPACE
    required: true

objects:
  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: custom-namespace-k8s-api-communication
      labels:
        created-by: cas-pipeline
    spec:
      description: |
        Allow all pods in namespace to communicate with the k8s api
      source:
        - - $namespace=${NAMESPACE}
      destination:
        - - int:network=internal-cluster-api-endpoint
