apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: namespace
    displayName: namespace
    name: NAMESPACE
    required: true

objects:
  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: custom-deployer-namespace-communication
      labels:
        created-by: cas-pipline
    spec:
      description: |
        Allow deployer role (ship-it) to communicate with namespace
      source:
        - - role=deployer
      destination:
        - - $namespace=${NAMESPACE}
