apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: airflow_prefix
    displayName: airflow_prefix
    name: AIRFLOW_PREFIX
    required: true
  - description: ggircs_prefix
    displayName: ggircs_prefix
    name: GGIRCS_PREFIX
    required: true
  - description: ciip_prefix
    displayName: ciip_prefix
    name: CIIP_PREFIX
    required: true

objects:
  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
    name: custom-deployer-all-namespaces-communication
    label:
      created-by: cas-pipline
  spec:
    description: |
      Allow deployer role (ship-it) to communicate with all namespaces
    source:
      - - role=deployer
    destination:
      - - $namespace=${AIRFLOW_PREFIX}-dev
      - - $namespace=${GGIRCS_PREFIX}-dev
      - - $namespace=${CIIP_PREFIX}-dev
      - - $namespace=${AIRFLOW_PREFIX}-test
      - - $namespace=${GGIRCS_PREFIX}-test
      - - $namespace=${CIIP_PREFIX}-test
      - - $namespace=${AIRFLOW_PREFIX}-prod
      - - $namespace=${GGIRCS_PREFIX}-prod
      - - $namespace=${CIIP_PREFIX}-prod
