apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: {{ .Values.elasticsearch.port.rest }}
      name: rest
    - port: {{ .Values.elasticsearch.port.internode }}
      name: inter-node
