apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    "app.kubernetes.io/part-of": efk-stack
spec:
  selector:
    app: kibana
  ports:
    - name: kibana
      port: {{ .Values.kibana.port }}
