apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.namespace }}
  labels:
    "app.kubernetes.io/part-of": efk-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: {{ .Values.kibana.image }}:{{ .Values.kibana.version }}
          resources:
            requests:
              cpu: {{ .Values.kibana.cpuRequest }}
              memory: {{ .Values.kibana.memoryRequest }}
          env:
            - name: ELASTICSEARCH_URL
              value: {{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port.rest }}
          ports:
            - containerPort: {{ .Values.kibana.port }}
