apiVersion: artifactory.devops.gov.bc.ca/v1alpha1
kind: ArtifactoryServiceAccount
metadata:
  labels: {{ include "cas-provision-artifactory.labels" . | nindent 4 }}
  name: cas-artifact-download
spec:
  descriptor: Artifactory service accounts to download artifacts from Artifactory
