apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-aggregator-logging-config
  namespace: {{ .Release.Namespace }}
data:
  vector-aggregator.yaml: |
    api:
      enabled: true
      address: 0.0.0.0:8686
    sources:
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "2"
    transforms:
      add_missing_timestamp:
        type: remap
        inputs: [vector]
        source: |
          .["@timestamp"] = format_timestamp!(.timestamp ?? now(), "%Y-%m-%dT%H:%M:%SZ")
    sinks:
      stdout:
        type: console
        inputs: [vector]
        encoding:
          codec: json
