apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-aggregator-logging-config
  namespace: {{ .Release.Namespace }}
data:
  vector-aggregator.yaml: |
    api:
      enabled: true
      address: 0.0.0.0:8686
    sources:
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "2"
    transforms:
      add_missing_timestamp:
        type: remap
        inputs: [vector]
        source: |
          .["@timestamp"] = format_timestamp!(.timestamp ?? now(), "%Y-%m-%dT%H:%M:%SZ")
    sinks:
      stdout:
        type: console
        inputs: [vector]
        encoding:
          codec: json
      elasticsearch:
        endpoints: ["http://{{ .Values.host }}:9200"]
        auth:
          user: "SECRET[backend_env.username]"
          password: "SECRET[backend_env.password]"
        bulk:
          # prefix comes from the parent helm chart values.
          # app_name is Vector Template syntax enclosed in backticks to avoid helm template interpolation.
          index: "{{ .Values.prefix }}-{{`{{ app_name }}`}}-%Y.%m"
        buffer:
          max_size: 4MB
          type: memory
