apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    vendor: crunchydata
{{ include "crunchy-monitoring.labels" . | indent 4 }}
  name: grafanadata
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
