apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: GitHub Login of the user to add to the namespace
    displayName: GitHub Login
    name: GH_LOGIN
    required: true
  - description: GitHub Team of the user to add to the namespace
    displayName: GitHub Team
    name: GH_TEAM
    required: true
  - description: namespace
    displayName: namespace
    name: NAMESPACE
    required: true
  - description: The ClusterRole to bind to this user
    displayName: Role
    name: ROLE

objects:
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ${GH_LOGIN}@github-${ROLE}
      namespace: ${NAMESPACE}
      labels:
        created-by: cas-pipeline
        gh-team: ${GH_TEAM}
    subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: ${GH_LOGIN}@github
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: ${ROLE}
