kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-job-runner
  labels:
{{ include "cas-provision.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-job-runner
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-job-runner
    namespace: {{ .Values.serviceAccounts.namespace }}
