{{ if eq template "namespacePrefix" .  .Values.namespacePrefixes.airflow }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-job-runner
  labels:
{{ include "cas-provision.labels" . | indent 4 }}

{{ end }}
