apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: crunchy-grafana
  namespace: {{ .Values.namespace }}
  labels:
{{ include "crunchy-monitoring.labels" . | indent 4 }}
spec:
  port:
    targetPort: grafana-proxy
  tls:
    termination: edge
  to:
    kind: Service
    name: crunchy-grafana
    weight: 100
  wildcardPolicy: None
