{{- $grafanaPassword := (randAlphaNum 32) | b64enc | quote }}
apiVersion: v1
data:
  password: {{ $grafanaPassword }}
  username: grafanaUser
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    vendor: crunchydata
{{ include "crunchy-monitoring.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
  name: grafana-secret
  namespace: {{ .Values.namespace }}
type: Opaque
