{{- $user := (randAlphaNum 32) | b64enc | quote }}
{{- $pass := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := print ("grafana-secret") }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- $user = index $secret.data "user" }}
{{- $pass = index $secret.data "pass" }}
{{- end -}}
apiVersion: v1
data:
  password: {{ $user }}
  username: {{ $pass }}
kind: Secret
metadata:
  labels:
    vendor: crunchydata
  annotations:
    "helm.sh/hook": "pre-install"
{{ include "crunchy-monitoring.labels" . | indent 4 }}
  name: grafana-secret
  namespace: {{ .Values.namespace }}
type: Opaque
