apiVersion: v1
data:
  password: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  labels:
    vendor: crunchydata
{{ include "crunchy-monitoring.labels" . | indent 4 }}
  name: grafana-secret
  namespace: {{ .Values.namespace }}
type: Opaque
