apiVersion: v1



apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: namespace
    displayName: namespace
    name: NAMESPACE
    required: true
  - description: airflow_namespace
    displayName: airflow_namespace
    name: AIRFLOW_NAMESPACE
    required: true
  - description: ggircs_namespace
    displayName: ggircs_namespace
    name: GGIRCS_NAMESPACE
    required: true
  - description: ciip_namespace
    displayName: ciip_namespace
    name: CIIP_NAMESPACE
    required: true

objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: cas-namespaces
      namespace: ${NAMESPACE}
    type: Opaque
    stringData:
      airflow-namespace: ${AIRFLOW_NAMESPACE}
      ggircs-namespace: ${GGIRCS_NAMESPACE}
      ciip-namespace: ${CIIP_NAMESPACE}
