apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    name: crunchy-grafana
    vendor: crunchydata
{{ include "crunchy-monitoring.labels" . | indent 4 }}
  name: crunchy-grafana
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: grafana
    port: 3000
  - name: grafana-proxy
    port: 9091
    protocol: TCP
    targetPort: grafana-proxy
  selector:
    name: crunchy-grafana
  type: ClusterIP
