apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    name: crunchy-prometheus
    vendor: crunchydata
{{ include "crunchy-monitoring.labels" . | indent 4 }}
  name: crunchy-prometheus
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: prometheus
    port: 9090
  selector:
    name: crunchy-prometheus
  type: ClusterIP
