apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator-monitoring
    name: crunchy-prometheus
    vendor: crunchydata
  name: crunchy-prometheus
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: prometheus
    port: 9090
  selector:
    name: crunchy-prometheus
  type: ClusterIP
