apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator-monitoring
    name: crunchy-alertmanager
    vendor: crunchydata
{{ include "crunchy-monitoring.labels" . | indent 4 }}
  name: crunchy-alertmanager
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: alertmanager
    port: 9093
  selector:
    name: crunchy-alertmanager
  type: ClusterIP
