{{ if eq .Release.Namespace .Values.deployer.namespace }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-deployer
  labels:
{{ include "cas-provision.labels" . | indent 4 }}
  namespace: {{ .Values.deployer.namespace }}
imagePullSecrets:
  - name: {{ .Values.docker.secretName }}

{{ end }}
